/*DATAMIGRATION 15F6D65E-37BE-4F08-843D-77CE2FE0CC77*/ -- Change the script's code only if the it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'FoodOrder', 'OrderState';
EXEC Rhetos.DataMigrationUse 'FoodOrder', 'OrderState', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'FoodOrder', 'OrderState', 'Initialization', 'bit';
EXEC Rhetos.DataMigrationUse 'FoodOrder', 'OrderState', 'Cancelled', 'bit';
EXEC Rhetos.DataMigrationUse 'FoodOrder', 'OrderState', 'Confirmed', 'bit';
EXEC Rhetos.DataMigrationUse 'FoodOrder', 'OrderState', 'Placed', 'bit';
EXEC Rhetos.DataMigrationUse 'FoodOrder', 'OrderState', 'Ready', 'bit';
EXEC Rhetos.DataMigrationUse 'FoodOrder', 'OrderState', 'Completed', 'bit';
EXEC Rhetos.DataMigrationUse 'FoodOrder', 'OrderState', 'Name', 'nvarchar(100)';
GO

IF NOT EXISTS (SELECT * FROM _FoodOrder.OrderState WHERE Initialization = 1)
	INSERT INTO _FoodOrder.OrderState(ID, Initialization, Name) SELECT NEWID(), 1, 'Initialization';
IF NOT EXISTS (SELECT * FROM _FoodOrder.OrderState WHERE Cancelled = 1)
	INSERT INTO _FoodOrder.OrderState(ID, Cancelled, Name) SELECT NEWID(), 1, 'Cancelled';
IF NOT EXISTS (SELECT * FROM _FoodOrder.OrderState WHERE Confirmed = 1)
	INSERT INTO _FoodOrder.OrderState(ID, Confirmed, Name) SELECT NEWID(), 1, 'Confirmed';
IF NOT EXISTS (SELECT * FROM _FoodOrder.OrderState WHERE Placed = 1)
	INSERT INTO _FoodOrder.OrderState(ID, Placed, Name) SELECT NEWID(), 1, 'Placed';
IF NOT EXISTS (SELECT * FROM _FoodOrder.OrderState WHERE Ready = 1)
	INSERT INTO _FoodOrder.OrderState(ID, Ready, Name) SELECT NEWID(), 1, 'Ready';
IF NOT EXISTS (SELECT * FROM _FoodOrder.OrderState WHERE Completed = 1)
	INSERT INTO _FoodOrder.OrderState(ID, Completed, Name) SELECT NEWID(), 1, 'Completed';

UPDATE _FoodOrder.OrderState SET Initialization = COALESCE(Initialization, 0),
	Cancelled = COALESCE(Cancelled, 0),
	Confirmed = COALESCE(Confirmed, 0),
	Placed = COALESCE(Placed, 0),
	Ready = COALESCE(Ready, 0),
	Completed = COALESCE(Completed, 0)
	
EXEC Rhetos.DataMigrationApplyMultiple 'FoodOrder', 'OrderState', 'ID, Initialization, Cancelled, Confirmed, Placed, Ready, Completed';
